---
- name: Add Amazon Corretto GPG key
  ansible.builtin.get_url:
    url: https://apt.corretto.aws/corretto.key
    dest: /usr/share/keyrings/corretto-keyring.asc
    mode: "0644"

- name: Add Amazon Corretto repository
  ansible.builtin.apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/corretto-keyring.asc] https://apt.corretto.aws stable main"
    filename: corretto
    state: present

- name: Install Amazon Corretto JDK 11
  ansible.builtin.apt:
    name: java-11-amazon-corretto-jdk
    state: present
    update_cache: true
